version: "3.7"
services:
  database:
    image: mongo:4.4
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MONGO_INITDB_DATABASE=${DB_NAME}
      - MONGO_INITDB_USERNAME=${DB_APP_USER}
      - MONGO_INITDB_PASSWORD=${DB_APP_PASS}
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./db:/data/db